import type { Metadata } from 'next';
import './globals.css';
import { pretendard } from '@/utils/font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable} antialiased app-container`}>
      <body className="app-wrapper">{children}</body>
    </html>
  );
}
